### ISSUE TITLE
[BUG] - Documentation

### ISSUE THREAD

**Issue by waynetheisinger** [jitesoft/docker-phpunit#3]
**Context**
It took me a long time (a whole afternoon) to work out that to get the xdebug debugger to break I needed to set the XDEBUG_MODE ENV   

```yml
phpunit:
    container_name: phpunit
    image: jitesoft/phpunit:8.2
    environment:
      - "XDEBUG_MODE=debug"
    volumes:
      - "./php:/app/"
      - "./conf/phpunit/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - "./conf/phpunit/xdebug.log:/var/log/xdebug.log"
```

**Expected outcome**

That reading the README here - or at [Docker Hub](https://hub.docker.com/r/jitesoft/phpunit/) would give me all the information that I would need to get up and running quickly.

**Actual outcome**

It took me a long time (a whole afternoon) to work out that to get the xdebug debugger to break

**Description**

This is a placeholder description of the solution, because I'm actually going to put in a PR with the documentation change. And reference this issue.

**Minimal reproducible test case**

Read the docs
